# 1. Conexion a PostgreSQL
spring.datasource.url=jdbc:postgresql://db:5432/encuestas_db
spring.datasource.username=admin
spring.datasource.password=fer777

# 2. Configuracion de Hibernate
# update permite que Spring cree las tablas en PostgreSQL automaticamente al leer la carpeta models
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Esto imprimira en la consola las sentencias SQL que Spring ejecuta por detras
spring.jpa.show-sql=true

# 3. Exclusion temporal de Spring Security
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration